var posts = [
{action: "Travel",
subject: "Sydney, Australia",
tags: ["Wildlife"],
content: "The penguins of Sydney Harbour are an unknown gem in the big city.  This species of tiny penguin return to their birthplace every year to foster their own young.  The population is often minimal, and sometimes non-existant, but it's worth a shot during the evening before dusk.  Be sure to keep your distance.  Sightings are often by the marina and in the west side of the bay.",
upvotes: 67,
downvotes: 12,
id: "1234"},

{action: "Live",
subject: "555 Haight St, San Francisco, CA",
tags: [],
content: "Do not rent a room in this apartment! There is a bar directly below the entire apartment which plays incredibly load music to around 2am most weekdays. The biggest problem is that they play the bass so loud that the entire apartment vibrates. So earplugs aren't much help when you can feel the music in your chest! My roomates and I asked for a minor compensation for the immense inconvenience, however the landlords had none of it.",
upvotes: 24,
downvotes: 3,
id: "1235"},

{action: "Learn",
subject: "Algorithms",
tags: ["Expert"],
content: "The Art of Computer Programming gives unparalleled depth on many subjects. You'll find a deep analysis of some very important concepts, and pick up some strategies that will WOW those in technical job interviews.",
upvotes: 64,
downvotes: 6,
id: "1236"},

{action: "Travel",
subject: "Sydney, Australia",
tags: ["Adventure"],
content: "If you get the incredible opportunity to visit this city, definitely condsider walking along the top of the Sydney Harbour Bridge. You heard me correctly: I said walking along the top of it! It's a guided tour and you're strapped to the bridge by a harness the entire time so it's completely safe. And it's great for all ages, too. I did it with my 8-year-old son and my father (who will be 70 this May). It's a little on the pricey side (around $400 per person), but definitley worth the view and the adventure factor.",
upvotes: 79,
downvotes: 2,
id: "1234a"},

{action: "Play",
subject: "Beach Volleyball",
tags: ["Toronto"],
content: "If you're in a youth age group and are planning to play competitively for an entire summer, definitely consider playing up an age group (or even two) for at least a couple tournaments. Not only will the more advanced play improve you significantly, but all the best youth teams do this. So if you don't, then you might have good results during the season, but you'll get skunked at provincials and nationals when all the best youth teams drop down to play in their own age group for the really important tournaments.",
upvotes: 909,
downvotes: 88,
id: "1237"},

{action: "Staying",
subject: "Brookline, Massachusetts",
tags: [],
content: "If you'll be staying in this beautiful Boston suburb for any amount of time, consider staying at the Marion Inn at 105 Marion Street. It's an old Victorian house with nice, confortable rooms at reasonable prices. It's also a 5 minute walk from Coolidge Corner, the heart of downtown Brookline that has quite a few perks. I spent 4 months in Boston for an internship and stayed at the Marion Inn the entire time. They do nightly and weekly rentals as well.",
upvotes: 16,
downvotes: 0,
id: "1238"},

{action: "Fly",
subject: "Belize",
tags: [],
content: "If you are planning to fly to Belize, consider taking a cheap flight to Mexico and then busing the rest of the way. You can end up saving a lot of money in return for sitting on a bus for the last 4 hours of your trip.",
upvotes: 111,
downvotes: 2,
id: "1239"},

{action: "Visiting",
subject: "Essex County, Southern Ontario, Canada",
tags:[],
content:"If you happen to find yourself in this area (near Windsor, Ontario) during the summer time, make sure to visit the Dairy Freeze.  It is a local favourite diner and ice-cream shop that serves soft serve ice cream cones bigger than you've ever seen!",
upvotes:10,
downvotes:1,
id:"34357370198149956243"},

{action:"Watching",
subject:"Red Sox Game from Green Monster Standing Room",
tags:[],
content:"If you want to go to a Red Sox game and are considering buying tickets to the Green Monster standing room, you should know that they sell way more standing room tickets than there is room for people to stand.  So if you get to the game less than 30 minutes early, there likely won't be any room along the standing room section and you'll have to find some other awkward place to stand (on a set of stairs, for example).  So either go early or consider some other tickets.",
upvotes:334,
downvotes:3,
id:"48704713950215891091"},

{action:"Buying",
subject:"Time Share in Florida",
tags:[],
content:"If you are considering buying a time share here, then you definitely need to reconsider.  Did you know that once you sign into a time share contract, you are required to pay the fees for eternity (unless you can manage to sell it to somebody else).  That means that your next of kin will inherit the time share from you and have to legally keep paying the fees.  It sounds like this couldn't possibly be legal, but it somehow is.  So if you are going to buy a time share, consider consulting all your current (and future?) decendants.",
upvotes:11067,
downvotes:0,
id:"84220446842375510932"}
];

module.exports = posts;
